routes/web.php
<?php

use App\Http\Controllers\UsersController;
use App\Http\Controllers\admins;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::resource('users', 'UsersController', ['only' => ['edit', 'update']]);
    Route::resource('companies/{company}/branch/{branch}/staff', 'ClientStaffController', ['names' => 'branches.staff', 'parameters' => ['staff' => 'user']]);
    Route::resource('companies/{company}/admin', 'ClientAdminController', ['only' => ['store', 'destroy'], 'names' => 'company.staff', 'parameters' => ['admin' => 'user']]);

    // Company (branches).
    Route::get('/company/{company}/branches', 'ClientCompanyController@branches')->name('client.company.branches');
    Route::get('/company/{company}/admins', 'ClientCompanyController@admins')->name('client.company.admins');
    Route::get('/company/{company}/branches/create', 'ClientCompanyController@createBranch')->name('client.company.branches.create');
    Route::post('/company/{company}/branches', 'ClientCompanyController@storeBranch')->name('client.company.branches.store');
});

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'roles:admins']], function () {
    // GET.
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/reports', 'ReportsController@index')->name('reports.index');
    
    // Companies.
    Route::resource('companies', 'CompaniesController');
    Route::get('/companies/{company}/admins', 'CompaniesController@admins')->name('companies.admins');

    // Branches.
    Route::resource('companies/{company}/branches', 'BranchesController');
    Route::get('/companies/{company}/branches/{branch}/orders', 'BranchesController@orders')->name('branches.orders');
    Route::get('/companies/{company}/branches/{branch}/members', 'BranchesController@members')->name('branches.members');

    // Refactored Controllers.
    Route::resource('products', 'ProductsController');
    Route::resource('orders', 'OrdersController', ['only' => ['index', 'show', 'update']]);
    Route::resource('staff', 'StaffController', ['parameters' => ['staff' => 'user']]);

    // Notifications
    Route::get('notifications', 'NotificationsController@index');
    Route::get('notifications/read', 'NotificationsController@read');
});

Route::group(['prefix' => 'branch/{branch}', 'middleware' => ['auth', 'roles:clients']], function () {
    // General.
    Route::get('/', 'ClientHomeController@index')->name('client.home');
    Route::get('/services', 'ClientServicesController@index')->name('client.services.index');
    Route::get('/reports', 'ClientReportsController@index')->name('client.reports.index');

    // Company.
    Route::get('/company/{company}', 'ClientCompanyController@index')->name('client.company.index');
    Route::patch('/company/{company}/update_company', 'ClientCompanyController@updateCompany')->name('client.company.update-company');
    Route::patch('/company/{company}/update_branch', 'ClientCompanyController@updateBranch')->name('client.company.update-branch');

    // History.
    Route::get('/history', 'ClientHistoryController@index')->name('client.history.index');
    Route::get('/history/{order}', 'ClientHistoryController@show')->name('client.history.show');

    // Quote.
    Route::get('/quote', 'ClientProductsController@index')->name('client.products.index');
    Route::get('/quote/{quote}/add', 'ClientProductsController@add')->name('client.products.add');
    Route::get('/quote/{quote}/checkout', 'ClientProductsController@checkout')->name('client.products.checkout');
    Route::post('/quote/{quote}/make_checkout', 'ClientProductsController@store')->name('client.quote.make-checkout');
    Route::get('/quote/complete', 'ClientProductsController@complete')->name('client.quote.complete');
});

// Change password after invite an user.
Route::get('/complete/{token}', 'UsersController@complete')->name('users.complete');
Route::patch('/complete/{token}', 'UsersController@completeProfile')->name('users.complete-profile');

Route::get('/', function () { return redirect()->route('login'); });
Route::get('/home', 'HomeController@branch')->middleware(['auth']);
Route::get('/change_branch', 'ClientHomeController@branch')->middleware('auth');
Route::get('/register', function () { return abort(404); }); // Register not needed.

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Order extends Model
{
    const STATUS_NEW = 'new';
    const STATUS_PENDING = 'pending';
    const STATUS_PAYED = 'payed';
    const STATUS_DELIVERED = 'delivered';
    const STATUS_COMPLETED = 'completed';
    const STATUS_CANCELED = 'canceled';

    const ALL_STATUS = [
        Order::STATUS_NEW,
        Order::STATUS_PENDING,
        Order::STATUS_PAYED,
        Order::STATUS_DELIVERED,
        Order::STATUS_COMPLETED,
        Order::STATUS_CANCELED,
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'status', 'data', 'user_id', 'total',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'data' => 'array'
    ];

    /**
     *
     */
    public function branch(): BelongsTo
    {
        return $this->belongsTo(Branch::class);
    }

    /**
     *
     */
    public function company(): BelongsTo
    {
        return $this->branch->company();
    }

    /**
     *
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     *
     */
    public function products(): BelongsToMany
    {
    	return $this->belongsToMany(Product::class, 'order_has_product')->withPivot([
    		'quantity',
    		'price',
    	]);
    }

    /**
     * Returns a css class based on the status of this order
     */
    public function getStatusClassAttribute(): String
    {
        // switch ($this->status) {
        //     case self::STATUS_NEW:
        //         return 'new';
        //     case self::STATUS_PENDING:
        //         return 'pending';
        //     case self::STATUS_PAYED:
        //         return 'payed';
        //     case self::STATUS_DELIVERED:
        //         return 'delivered';
        //     case self::STATUS_COMPLETED:
        //         return 'completed';
        //     case self::STATUS_COMPLETED:
        //         return 'canceled';
        // }
        
        return $this->status;
    }

    /**
     *
     */
    public function getVatAttribute()
    {
        return $this->company->country->vat;
    }
}

app/Http/Controllers/OrdersController.php
<?php

namespace App\Http\Controllers;

use App\Order;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;

class OrdersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $orders = Order::query();

        if ($request->status) {
            $orders = $orders->where('status', $request->status);
        }

        if ($request->id) {
            $orders = $orders->where('id', $request->id);
        }

        return view('sections.orders.index', [
            'orders' => $orders->orderBy('id', 'DESC')->paginate(50)->appends(Input::except('page')),
            'orders_count' => $orders->count(),
            'id' => $request->id,
            'status' => $request->status,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        $statuses = collect([
            Order::STATUS_NEW => __('app.status.new'),
            Order::STATUS_PENDING => __('app.status.pending'),
            Order::STATUS_PAYED => __('app.status.payed'),
            Order::STATUS_DELIVERED => __('app.status.delivered'),
            Order::STATUS_COMPLETED => __('app.status.completed'),
            Order::STATUS_CANCELED => __('app.status.canceled'),
        ]);

        return view('sections.orders.show', [
            'order' => $order,
            'statuses' => $statuses,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $order = Order::find($id);
        $order->update(['status' => $request->status]);

        if ($request->ajax()) {
            return response(null, 204);
        }

        return redirect()->route('orders.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/sections/orders/index.blade.php
@extends('containers.content')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <form class="search-bar" method="GET" action="{{ action('OrdersController@index') }}">
                <div class="form-search">
                    <i class="fa fa-search icon"></i>
                    <input id="search" type="text" class="form-input" name="id" placeholder="Buscar Pedidos" value="{{ $id }}">
                </div>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <ul class="tabs md">
                <li class="tab-item {{ $status == null ? 'active' : '' }}">
                    <a href="{{ route('orders.index') }}">Todas</a>
                </li>
                
                <li class="tab-item {{ $status == App\Order::STATUS_PENDING ? 'active' : '' }}">
                    <a href="{{ route('orders.index', ['status' => App\Order::STATUS_PENDING]) }}">
                        Pendientes ({{ App\Order::where('status', App\Order::STATUS_PENDING)->count() }})
                    </a>
                </li>
                
                <li class="tab-item {{ $status == App\Order::STATUS_COMPLETED ? 'active' : '' }}">
                    <a href="{{ route('orders.index', ['status' => App\Order::STATUS_COMPLETED]) }}">
                        Completadas ({{ App\Order::where('status', App\Order::STATUS_COMPLETED)->count() }})
                    </a>
                </li>

                <li class="tab-item {{ $status == App\Order::STATUS_DELIVERED ? 'active' : '' }}">
                    <a href="{{ route('orders.index', ['status' => App\Order::STATUS_DELIVERED]) }}">
                        Enviados ({{ App\Order::where('status', App\Order::STATUS_DELIVERED)->count() }})
                    </a>
                </li>

                <li class="tab-item {{ $status == App\Order::STATUS_PAYED ? 'active' : '' }}">
                    <a href="{{ route('orders.index', ['status' => App\Order::STATUS_PAYED]) }}">
                        Pagados ({{ App\Order::where('status', App\Order::STATUS_PAYED)->count() }})
                    </a>
                </li>

                <li class="tab-item {{ $status == App\Order::STATUS_NEW ? 'active' : '' }}">
                    <a href="{{ route('orders.index', ['status' => App\Order::STATUS_NEW]) }}">
                        Nuevos ({{ App\Order::where('status', App\Order::STATUS_NEW)->count() }})
                    </a>
                </li>

                <li class="tab-item {{ $status == App\Order::STATUS_CANCELED ? 'active' : '' }}">
                    <a href="{{ route('orders.index', ['status' => App\Order::STATUS_CANCELED]) }}">
                        Cancelados ({{ App\Order::where('status', App\Order::STATUS_CANCELED)->count() }})
                    </a>
                </li>
            </ul>

            <div class="table table-orders">
                <table>
                    @if ($orders->count())
                        <thead>
                            <tr>
                                <th class="col-id">Nº</th>
                                <th class="col-date">Fecha</th>
                                <th class="col-status">Status</th>
                                <th class="col-company">Empresa</th>
                                <th class="col-branch">Edificio</th>
                                <th class="col-author">Realizado por</th>
                            </tr>
                        </thead>
                    @endif

                    <tbody>
                        @foreach ($orders as $order)
                        <tr class="{{ $order->status }}">
                            <td class="col-id">
                                <a href="{{ route('orders.show', ['order' => $order->id]) }}">{{ $order->id }}</a>
                            </td>
                            <td class="col-date">
                                <a href="{{ route('orders.show', ['order' => $order->id]) }}">{{ $order->created_at->format('d M Y - h:m a') }}</a>
                            </td>
                            <td class="col-status">
                                <a href="{{ route('orders.show', ['order' => $order->id]) }}">
                                    <div class="status-tag {{ $order->status_class }}">{{ __('app.status.'.$order->status) }}</div>
                                </a>
                            </td>
                            <td class="col-company">
                                <a href="{{ route('orders.show', ['order' => $order->id]) }}">{{ $order->company->name }}</a>
                            </td>
                            <td class="col-branch">
                                <a href="{{ route('orders.show', ['order' => $order->id]) }}">{{ $order->branch->name }}</a>
                            </td>
                            <td class="col-author">
                                <a href="{{ route('orders.show', ['order' => $order->id]) }}">{{ $order->user->name }}</a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>

                {{ $orders->links() }}

                @if (!$orders->count())
                    <div class="table-empty">
                        <p>Sin pedidos</p>
                    </div>
                @endif
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/sections/orders/show.blade.php
@extends('containers.content')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="form-field form-field-inline">
                <label for="status" class="form-label">Status</label>
                <div class="v-preloading preloading-status"></div>
                <app-change-status
                    url="{{ route('orders.update', ['order' => $order->id]) }}"
                    :statuses='{!! $statuses !!}'
                    current_status="{{ $order->status }}"/>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-5 col-xl-3">
            <div class="order-card">
                <p class="order-card-author">{{ $order->user->name }}</p>
                <p class="order-card-street">{{ $order->branch->street }} {{ $order->branch->neighborhood }} {{ $order->branch->number_ext }} {{ $order->branch->number_int }}</p>
                <p class="order-card-country">{{ $order->branch->city }} {{ $order->branch->state }} CP: {{ $order->branch->zipcode }}</p>
                <p class="order-card-phone">Phone: {{ $order->branch->phone }}</p>
                <p class="order-card-email">Pais: {{ $order->branch->company->country->name }}</p>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="table table-order-detail">
                <table>
                    <thead>
                        <tr>
                            <th class="col-image"></th>
                            <th class="col-quantity">Cantidad</th>
                            <th class="col-product">Producto</th>
                            <th class="col-description">Descripción</th>
                            <th class="col-category">Categoría</th>
                            <th class="col-unit-price">Precio unitario</th>
                            <th class="col-total">Total</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach ($order->products as $product)
                            <tr>
                                <td class="col-image">
                                    <div class="product-image">
                                        <img src="{{ $product->image }}" alt="{{ $product->name }}">
                                    </div>
                                </td>
                                <td class="col-quantity">{{ $product->pivot->quantity }}</td>
                                <td class="col-product">{{ $product->name }}</td>
                                <td class="col-description">{{ $product->description }}</td>
                                <td class="col-category">{{ $product->category->name }}</td>
                                <td class="col-unit-price">${{ number_format($product->pivot->price, 2) }}</td>
                                <td class="col-total">${{ number_format($product->pivot->price * $product->pivot->quantity, 2) }}</td>
                            </tr>
                        @endforeach

                        <tr>
                            <td class="col-subtotal" colspan="6">Subtotal</td>
                            <td class="col-subtotal">{{ number_format($order->total, 2) }}</td>
                        </tr>

                        <tr>
                            <td class="col-iva" colspan="6">IVA</td>
                            <td class="col-iva">{{ number_format($order->total * $order->vat, 2) }}</td>
                        </tr>

                        <tr>
                            <td class="col-total-all" colspan="6">Total</td>
                            <td class="col-total-all">{{ number_format($order->total * (1 + $order->vat), 2) }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection