routes/web.php
<?php

use App\Http\Controllers\UsersController;
use App\Http\Controllers\admins;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::resource('users', 'UsersController', ['only' => ['edit', 'update']]);
    Route::resource('companies/{company}/branch/{branch}/staff', 'ClientStaffController', ['names' => 'branches.staff', 'parameters' => ['staff' => 'user']]);
    Route::resource('companies/{company}/admin', 'ClientAdminController', ['only' => ['store', 'destroy'], 'names' => 'company.staff', 'parameters' => ['admin' => 'user']]);

    // Company (branches).
    Route::get('/company/{company}/branches', 'ClientCompanyController@branches')->name('client.company.branches');
    Route::get('/company/{company}/admins', 'ClientCompanyController@admins')->name('client.company.admins');
    Route::get('/company/{company}/branches/create', 'ClientCompanyController@createBranch')->name('client.company.branches.create');
    Route::post('/company/{company}/branches', 'ClientCompanyController@storeBranch')->name('client.company.branches.store');
});

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'roles:admins']], function () {
    // GET.
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/reports', 'ReportsController@index')->name('reports.index');
    
    // Companies.
    Route::resource('companies', 'CompaniesController');
    Route::get('/companies/{company}/admins', 'CompaniesController@admins')->name('companies.admins');

    // Branches.
    Route::resource('companies/{company}/branches', 'BranchesController');
    Route::get('/companies/{company}/branches/{branch}/orders', 'BranchesController@orders')->name('branches.orders');
    Route::get('/companies/{company}/branches/{branch}/members', 'BranchesController@members')->name('branches.members');

    // Refactored Controllers.
    Route::resource('products', 'ProductsController');
    Route::resource('orders', 'OrdersController', ['only' => ['index', 'show', 'update']]);
    Route::resource('staff', 'StaffController', ['parameters' => ['staff' => 'user']]);

    // Notifications
    Route::get('notifications', 'NotificationsController@index');
    Route::get('notifications/read', 'NotificationsController@read');
});

Route::group(['prefix' => 'branch/{branch}', 'middleware' => ['auth', 'roles:clients']], function () {
    // General.
    Route::get('/', 'ClientHomeController@index')->name('client.home');
    Route::get('/services', 'ClientServicesController@index')->name('client.services.index');
    Route::get('/reports', 'ClientReportsController@index')->name('client.reports.index');

    // Company.
    Route::get('/company/{company}', 'ClientCompanyController@index')->name('client.company.index');
    Route::patch('/company/{company}/update_company', 'ClientCompanyController@updateCompany')->name('client.company.update-company');
    Route::patch('/company/{company}/update_branch', 'ClientCompanyController@updateBranch')->name('client.company.update-branch');

    // History.
    Route::get('/history', 'ClientHistoryController@index')->name('client.history.index');
    Route::get('/history/{order}', 'ClientHistoryController@show')->name('client.history.show');

    // Quote.
    Route::get('/quote', 'ClientProductsController@index')->name('client.products.index');
    Route::get('/quote/{quote}/add', 'ClientProductsController@add')->name('client.products.add');
    Route::get('/quote/{quote}/checkout', 'ClientProductsController@checkout')->name('client.products.checkout');
    Route::post('/quote/{quote}/make_checkout', 'ClientProductsController@store')->name('client.quote.make-checkout');
    Route::get('/quote/complete', 'ClientProductsController@complete')->name('client.quote.complete');
});

// Change password after invite an user.
Route::get('/complete/{token}', 'UsersController@complete')->name('users.complete');
Route::patch('/complete/{token}', 'UsersController@completeProfile')->name('users.complete-profile');

Route::get('/', function () { return redirect()->route('login'); });
Route::get('/home', 'HomeController@branch')->middleware(['auth']);
Route::get('/change_branch', 'ClientHomeController@branch')->middleware('auth');
Route::get('/register', function () { return abort(404); }); // Register not needed.

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Order extends Model
{
    const STATUS_NEW = 'new';
    const STATUS_PENDING = 'pending';
    const STATUS_PAYED = 'payed';
    const STATUS_DELIVERED = 'delivered';
    const STATUS_COMPLETED = 'completed';
    const STATUS_CANCELED = 'canceled';

    const ALL_STATUS = [
        Order::STATUS_NEW,
        Order::STATUS_PENDING,
        Order::STATUS_PAYED,
        Order::STATUS_DELIVERED,
        Order::STATUS_COMPLETED,
        Order::STATUS_CANCELED,
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'status', 'data', 'user_id', 'total',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'data' => 'array'
    ];

    /**
     *
     */
    public function branch(): BelongsTo
    {
        return $this->belongsTo(Branch::class);
    }

    /**
     *
     */
    public function company(): BelongsTo
    {
        return $this->branch->company();
    }

    /**
     *
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     *
     */
    public function products(): BelongsToMany
    {
    	return $this->belongsToMany(Product::class, 'order_has_product')->withPivot([
    		'quantity',
    		'price',
    	]);
    }

    /**
     * Returns a css class based on the status of this order
     */
    public function getStatusClassAttribute(): String
    {
        // switch ($this->status) {
        //     case self::STATUS_NEW:
        //         return 'new';
        //     case self::STATUS_PENDING:
        //         return 'pending';
        //     case self::STATUS_PAYED:
        //         return 'payed';
        //     case self::STATUS_DELIVERED:
        //         return 'delivered';
        //     case self::STATUS_COMPLETED:
        //         return 'completed';
        //     case self::STATUS_COMPLETED:
        //         return 'canceled';
        // }
        
        return $this->status;
    }

    /**
     *
     */
    public function getVatAttribute()
    {
        return $this->company->country->vat;
    }
}

app/Http/Controllers/ReportsController.php
<?php

namespace App\Http\Controllers;

use DatePeriod;
use App\Order;
use App\Branch;
use App\Company;
use Carbon\Carbon;
use Carbon\CarbonInterval;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;

class ReportsController extends Controller
{
    public function index (Request $request)
    {
        $companies = Company::all();
        $company = $companies->find($request->company_id);

        if (!$company) {
            return view('sections.reports.index', [
                'chart_data' => [],
                'orders' => collect([]),
                'companies' => $companies,
                'branches' => Branch::all(),
                'company_id' => $request->company_id,
                'branch_id' => $request->branch_id,
                'from' => null,
                'to' => null,
                'total' => collect([]),
            ]);
        }

        if ($request->branch_id == 'all') {
            $datas = [];
            $total = [];
            $orders = [];

            foreach ($company->branches as $branch) {
                array_push($datas, [
                    'name' => $branch->name,
                    'backgroundColor' => 'rgba(56, 91, 232, 0.2)',
                    'borderColor' => 'rgb(56, 91, 232)',
                    'data' => $this->fetchBranchData($branch),
                ]);

                array_push($orders, $branch->orders()
                    ->where('created_at', '>', Carbon::parse($request->from))
                    ->where('status', '!=', Order::STATUS_NEW)
                    ->orderBy('id', 'DESC')->get()
                );

                array_push($total, [
                    'name' => $branch->name,
                    'income' => $branch->orders()
                        ->where('status', Order::STATUS_COMPLETED)
                        ->select(DB::raw('SUM(total) as income'))
                        ->first()->income,
                ]);
            }

            array_unshift($total, [
                'name' => 'Total de compras',
                'income' => array_reduce(
                    array_map(function ($value) { return $value['income']; }, $total),
                    function ($a, $b) { return $a + $b; }
                )
            ]);

            return view('sections.reports.index', [
                'chart_data' => $datas,
                'orders' => collect($orders),
                'companies' => $companies,
                'branches' => Branch::all(),
                'company_id' => $request->company_id,
                'branch_id' => $request->branch_id,
                'from' => $request->from,
                'to' => $request->to,
                'total' => collect($total),
            ]);
        }

        $branch = Branch::find($request->branch_id);

        if (!$branch) {
            return view('sections.reports.index', [
                'chart_data' => [],
                'orders' => collect([]),
                'companies' => $companies,
                'branches' => Branch::all(),
                'company_id' => $request->company_id,
                'branch_id' => $request->branch_id,
                'from' => null,
                'to' => null,
                'total' => collect([]),
            ]);
        }

        $chart_data = [
            [
                'name' => $branch->name,
                'backgroundColor' => 'rgba(56, 91, 232, 0.2)',
                'borderColor' => 'rgb(56, 91, 232)',
                'data' => $this->fetchBranchData($branch),
            ]
        ];

        $total = $branch->orders()
            ->where('status', Order::STATUS_COMPLETED)
            ->select(DB::raw('SUM(total) as income'))
            ->first();
        
        $orders = $branch->orders()
            ->where('created_at', '>', Carbon::parse($request->from))
            ->where('status', '!=', Order::STATUS_NEW)
            ->orderBy('id', 'DESC')
            ->paginate(25);

        return view('sections.reports.index', [
            'chart_data' => $chart_data,
            'orders' => $orders,
            'companies' => $companies,
            'branches' => Branch::all(),
            'company_id' => $request->company_id,
            'branch_id' => $request->branch_id,
            'from' => $request->from,
            'to' => $request->to,
            'total' => collect([
                'name' => $branch->name,
                'income' => $total->income
            ]),
        ]);
    }


    /**
     *
     */
    public function fetchBranchData ($branch) {
        $chart_data = $branch->orders()
            ->where('created_at', '>', Carbon::now()->subYears(2)->setTime(23, 59, 59))
            ->where('status', '!=', Order::STATUS_NEW)
            ->select(
                DB::raw('COUNT(*) as orders'),
                DB::raw('SUM(total) as income'),
                DB::raw('DATE_FORMAT(created_at,\'%Y-%m-%d\') as day')
            )
            ->groupBy('day')
            ->get();

        $data = [];
        
        foreach ($chart_data as $cd) {
            $data[$cd->day] = [
                'orders' => $cd->orders,
                'income' => $cd->income,
                'day' => $cd->day,
            ];
        }
        
        $chart_data = $data;

        $begin = Carbon::now()->subYears(2)->setTime(23, 59, 59);
        $end = Carbon::now();
        $interval = CarbonInterval::day();
        $period = new DatePeriod($begin, $interval, $end);

        foreach ($period as $day) {
            if (!isset($chart_data[$day->format('Y-m-d')])) {
                $chart_data[$day->format('Y-m-d')] = [
                    'orders' => 0,
                    'income' => 0,
                    'day' => $day->format('Y-m-d'),
                ];
            }
        }

        ksort($chart_data);
        $data = [];
        
        foreach ($chart_data as $cd) {
            array_push($data, [
                'day' => $cd['day'],
                'orders' => $cd['orders'],
                'income' => $cd['income'],
            ]);
        }
        
        $chart_data = $data;

        return $chart_data;
    }
}

resources/views/sections/reports/index.blade.php
@extends('containers.content')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="filter-report-bar admin-report">
                <form method="GET" action="{{ action('ReportsController@index') }}">
                    <div class="row align-items-end">
                        <div class="filter-report-col">
                            <p class="filter-title">Filtrar por</p>
                        </div>

                        <div class="filter-report-col">
                            <div class="form-field">
                                <label for="from" class="form-label">Desde</label>
                                <input id="from" type="text" class="form-input" name="from" data-default="{{ $from }}" calendar="from">
                            </div>
                        </div>

                        <div class="filter-report-col">
                            <div class="form-field">
                                <label for="to" class="form-label">Hasta</label>
                                <input id="to" type="text" class="form-input" name="to" data-default="{{ $to }}" calendar="to">
                            </div>
                        </div>

                        <!-- <div class="filter-report-col">
                            <div class="form-field">
                                <label for="type" class="form-label">Tipo</label>
                                <div class="form-select">
                                    <select id="type" class="form-input" name="type">
                                        <option value="" selected>Selecciona el tipo</option>
                                    </select>

                                    <i class="fa fa-caret-down caret"></i>
                                </div>
                            </div>
                        </div> -->

                        <div class="multiple-filter-report-col">
                            <app-company-branch
                                company_id="{{ $company_id }}"
                                branch_id="{{ $branch_id }}"
                                :companies="{{ $companies }}"
                                :branches="{{ $branches }}"
                            />
                        </div>

                        <div class="filter-report-col">
                            <div class="form-field">
                                <input type="submit" class="btn btn-pri" value="Filtrar">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="col-md-12">
            <div class="quick-reports quick-summary-cards">
                <div class="dashboard-card">
                    @if ($total->count())
                        <div class="card-content">
                            @if ($total->has('name'))
                                <div class="field">
                                    <div class="field-label">{{ $total['name'] }}</div>
                                    <div class="field-value">${{ number_format($total['income'], 2) }}</div>
                                </div>
                            @else
                                @foreach ($total as $total_branch)
                                    <div class="field">
                                        <div class="field-label">{{ $total_branch['name'] }}</div>
                                        <div class="field-value">${{ number_format($total_branch['income'], 2) }}</div>
                                    </div>
                                @endforeach
                            @endif
                        </div>
                    @endif
                </div>
            </div>
        </div>

        <div class="col-md-12">
            <div class="preloading-chart-reports v-preloading"></div>
            <app-chart
                class="report-card"
                tag="client.orders"
                from="{{ $from }}"
                to="{{ $to }}"
                :entries="{{ json_encode($chart_data) }}"/>
        </div>

        <div class="col-md-12">
           <div class="table table-report-orders">
                <table>
                    @if ($orders->count())
                    <thead>
                        <tr>
                            <th class="col-id">Nº</th>
                            <th class="col-date">Fecha</th>
                            <th class="col-status">Status</th>
                            <th class="col-company">Empresa</th>
                            <th class="col-author">Realizado por</th>
                        </tr>
                    </thead>
                    @endif

                    <tbody>
                        @if ($branch_id === 'all')
                            @foreach ($orders as $branch)
                                @foreach ($branch as $order)
                                    <tr>
                                        <td class="col-id">
                                            <a href="{{ route('orders.show', ['order' => $order->id]) }}">{{ $order->id }}</a>
                                        </td>
                                        <td class="col-date">
                                            <a href="{{ route('orders.show', ['order' => $order->id]) }}">{{ $order->created_at->format('d M Y - h:m a') }}</a>
                                        </td>
                                        <td class="col-status">
                                            <a href="{{ route('orders.show', ['order' => $order->id]) }}">
                                                <div class="status-tag {{ $order->status_class }}">{{ __('app.status.'.$order->status) }}</div>
                                            </a>
                                        </td>
                                        <td class="col-company">
                                            <a href="{{ route('orders.show', ['order' => $order->id]) }}">{{ $order->company->name }}</a>
                                        </td>
                                        <td class="col-author">
                                            <a href="{{ route('orders.show', ['order' => $order->id]) }}">{{ $order->user->name }}</a>
                                        </td>
                                    </tr>
                                @endforeach
                            @endforeach
                        @else
                            @foreach ($orders as $order)
                                <tr>
                                    <td class="col-id">
                                        <a href="{{ route('orders.show', ['order' => $order->id]) }}">{{ $order->id }}</a>
                                    </td>
                                    <td class="col-date">
                                        <a href="{{ route('orders.show', ['order' => $order->id]) }}">{{ $order->created_at->format('d M Y - h:m a') }}</a>
                                    </td>
                                    <td class="col-status">
                                        <a href="{{ route('orders.show', ['order' => $order->id]) }}">
                                            <div class="status-tag {{ $order->status_class }}">{{ __('app.status.'.$order->status) }}</div>
                                        </a>
                                    </td>
                                    <td class="col-company">
                                        <a href="{{ route('orders.show', ['order' => $order->id]) }}">{{ $order->company->name }}</a>
                                    </td>
                                    <td class="col-author">
                                        <a href="{{ route('orders.show', ['order' => $order->id]) }}">{{ $order->user->name }}</a>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>

                @if (!$orders->count())
                <div class="table-empty">
                    <p>Sin ordenes en este edificio.</p>
                </div>
                @endif
            </div>
        </div>
    </div>
</div>
@endsection