routes/web.php
<?php

use App\Http\Controllers\UsersController;
use App\Http\Controllers\admins;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::resource('users', 'UsersController', ['only' => ['edit', 'update']]);
    Route::resource('companies/{company}/branch/{branch}/staff', 'ClientStaffController', ['names' => 'branches.staff', 'parameters' => ['staff' => 'user']]);
    Route::resource('companies/{company}/admin', 'ClientAdminController', ['only' => ['store', 'destroy'], 'names' => 'company.staff', 'parameters' => ['admin' => 'user']]);

    // Company (branches).
    Route::get('/company/{company}/branches', 'ClientCompanyController@branches')->name('client.company.branches');
    Route::get('/company/{company}/admins', 'ClientCompanyController@admins')->name('client.company.admins');
    Route::get('/company/{company}/branches/create', 'ClientCompanyController@createBranch')->name('client.company.branches.create');
    Route::post('/company/{company}/branches', 'ClientCompanyController@storeBranch')->name('client.company.branches.store');
});

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'roles:admins']], function () {
    // GET.
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/reports', 'ReportsController@index')->name('reports.index');
    
    // Companies.
    Route::resource('companies', 'CompaniesController');
    Route::get('/companies/{company}/admins', 'CompaniesController@admins')->name('companies.admins');

    // Branches.
    Route::resource('companies/{company}/branches', 'BranchesController');
    Route::get('/companies/{company}/branches/{branch}/orders', 'BranchesController@orders')->name('branches.orders');
    Route::get('/companies/{company}/branches/{branch}/members', 'BranchesController@members')->name('branches.members');

    // Refactored Controllers.
    Route::resource('products', 'ProductsController');
    Route::resource('orders', 'OrdersController', ['only' => ['index', 'show', 'update']]);
    Route::resource('staff', 'StaffController', ['parameters' => ['staff' => 'user']]);

    // Notifications
    Route::get('notifications', 'NotificationsController@index');
    Route::get('notifications/read', 'NotificationsController@read');
});

Route::group(['prefix' => 'branch/{branch}', 'middleware' => ['auth', 'roles:clients']], function () {
    // General.
    Route::get('/', 'ClientHomeController@index')->name('client.home');
    Route::get('/services', 'ClientServicesController@index')->name('client.services.index');
    Route::get('/reports', 'ClientReportsController@index')->name('client.reports.index');

    // Company.
    Route::get('/company/{company}', 'ClientCompanyController@index')->name('client.company.index');
    Route::patch('/company/{company}/update_company', 'ClientCompanyController@updateCompany')->name('client.company.update-company');
    Route::patch('/company/{company}/update_branch', 'ClientCompanyController@updateBranch')->name('client.company.update-branch');

    // History.
    Route::get('/history', 'ClientHistoryController@index')->name('client.history.index');
    Route::get('/history/{order}', 'ClientHistoryController@show')->name('client.history.show');

    // Quote.
    Route::get('/quote', 'ClientProductsController@index')->name('client.products.index');
    Route::get('/quote/{quote}/add', 'ClientProductsController@add')->name('client.products.add');
    Route::get('/quote/{quote}/checkout', 'ClientProductsController@checkout')->name('client.products.checkout');
    Route::post('/quote/{quote}/make_checkout', 'ClientProductsController@store')->name('client.quote.make-checkout');
    Route::get('/quote/complete', 'ClientProductsController@complete')->name('client.quote.complete');
});

// Change password after invite an user.
Route::get('/complete/{token}', 'UsersController@complete')->name('users.complete');
Route::patch('/complete/{token}', 'UsersController@completeProfile')->name('users.complete-profile');

Route::get('/', function () { return redirect()->route('login'); });
Route::get('/home', 'HomeController@branch')->middleware(['auth']);
Route::get('/change_branch', 'ClientHomeController@branch')->middleware('auth');
Route::get('/register', function () { return abort(404); }); // Register not needed.

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Underscore\Types\Strings;

class User extends Authenticatable
{
    use Notifiable;

    const TYPE_SUPERADMIN = 'superadmin';
    const TYPE_ADMIN = 'admin';
    const TYPE_CLIENT = 'client';
    const TYPE_STAFF = 'staff';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email',
        'type',
        'first_name',
        'last_name',
        'birthdate',
        'image',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'birthdate'
    ];

    /**
     *
     */
    public function staffing(): BelongsToMany
    {
        return $this->belongsToMany(Branch::class, 'branch_has_staff');
    }

    /**
     *
     */
    public function companies(): BelongsToMany
    {
        return $this->belongsToMany(Company::class, 'company_has_user')->withPivot([
            'role'
        ]);
    }

    /**
     *
     */
    public function branches(): BelongsToMany
    {
        return $this->belongsToMany(Branch::class, 'branch_has_user')->withPivot([
            'role'
        ]);
    }

    /**
     *
     */
    public function getImageAttribute($image)
    {
        if (!$image) {
            return null;
        }
        
        if (Strings::startsWith($image, 'http')) {
            return $image;
        }

        return asset(Strings::replace($image, 'public', 'storage'));
    }

    /**
     * Returns the user's full name
     */
    public function getFullNameAttribute()
    {
        return $this->getNameAttribute();
    }

    /**
     * Returns the user's full name
     */
    public function getNameAttribute()
    {
        return $this->first_name.' '.$this->last_name;
    }

    /**
     * Returns the user's full name
     */
    public function getInitialsAttribute()
    {
        return strtoupper($this->first_name[0].$this->last_name[0]);
    }
}

app/Http/Controllers/StaffController.php
<?php

namespace App\Http\Controllers;

use App\Branch;
use App\Company;
use App\Http\Requests\StaffUpdateRequest;
use App\User;
use Hash;
use Illuminate\Http\Request;
use Intervention\Image\ImageManagerStatic as Image;
use Underscore\Types\Arrays;
use Underscore\Types\Strings;

class StaffController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $admins = User::where('type', User::TYPE_ADMIN);
        $staff = User::where('type', User::TYPE_STAFF);
        
        if ($request->name) {
            $admins = $admins
                ->where('first_name', 'LIKE', '%'.$request->name.'%')
                ->orWhere('last_name', 'LIKE', '%'.$request->name.'%');

            $staff = $staff
                ->where('first_name', 'LIKE', '%'.$request->name.'%')
                ->orWhere('last_name', 'LIKE', '%'.$request->name.'%');
        }

        return view('sections.staff.index', [
            'admins' => $admins->get(),
            'staff' => $staff->get(),
            'name' => $request->name,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('sections.staff.create', [
            'companies' => Company::all(),
            'branches' => Branch::with('company')->get(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'first_name' => 'required|min:3',
            'last_name' => 'required|min:3',
            'birthdate' => 'nullable|date',
            'image' => 'image|dimensions:min_width=500,min_height=500',
        ];

        if ($request->email) {
            $rules = Arrays::merge($rules, ['email' => 'required|email']);
        }

        $request->validate($rules);

        $image = null;
        if ($request->hasFile('image') && $request->file('image')->isValid()) {
            $image = $request->image->store('public/avatars');
        }

        // Assign data depending of the role.
        $data = $request->only([
            'first_name', 'last_name', 'image', 'role'
        ]);

        if ($request->role == User::TYPE_ADMIN) {
            $data = Arrays::merge($data, [
                'email' => $request->email,
                'type' => User::TYPE_ADMIN,
            ]);
        }

        if ($request->role == User::TYPE_STAFF) {
            $data = Arrays::merge($data, [
                'branch_ids' => $request->branch_ids,
                'birthdate' => $request->birthdate,
                'type' => User::TYPE_STAFF,
                'email' => str_random(16).'@kleanservices.com',
                'password' => Hash::make(str_random(16)),
            ]);
        }

        $user = User::create(Arrays::merge($data, [
            'image' => $image,
        ]));

        $branches = [];

        if ($request->branch_ids) {
            $branches = $request->branch_ids;
        }

        // WARNING: I don't know what I'm doing.
        $user->staffing()->sync($branches);

        // TODO: send mail invitation.
        return redirect()->route('staff.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('sections.staff.create', [
            'companies' => Company::all(),
            'branches' => Branch::with('company')->get(),
            'user' => User::find($id)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StaffUpdateRequest $request, User $user)
    {
        $image = null;
        if ($request->hasFile('image') && $request->file('image')->isValid()) {
            $manager = Image::configure(['driver' => 'gd']);
            $image = Image::make($request->file('image')->getRealPath())->fit(500, 500);
            $extension = $request->file('image')->guessExtension();

            $name = str_random('32').'.'.$extension;
            $image = $image->save(storage_path('app/public/avatars/'.$name));
            $image = Strings::replace($image->dirname.'/'.$name, storage_path('app/'), '');
        }

        // Assign data depending of the role.
        $data = $request->only([
            'first_name', 'last_name', 'image', 'role'
        ]);

        if ($request->role == User::TYPE_ADMIN) {
            $data = Arrays::merge($data, [
                'email' => $request->email,
                'type' => User::TYPE_ADMIN,
            ]);
        }

        if ($request->role == User::TYPE_STAFF) {
            $data = Arrays::merge($data, [
                'branch_ids' => $request->branch_ids,
                'birthdate' => $request->birthdate,
                'email' => str_random(16).'@kleanservices.com',
                'password' => Hash::make(str_random(16)),
                'type' => User::TYPE_STAFF,
            ]);
        }
        
        $data = Arrays::merge($data, [
            'image' => $image !== null ? $image : $user->image,
        ]);

        $user->update($data);

        // WARNING: I don't know what I'm doing.
        $user->staffing()->sync($request->branch_ids);

        // TODO: send mail invitation.
        return redirect()->route('staff.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        if ($user && $user->type === User::TYPE_STAFF) {
            $user->staffing()->detach();
            $user->delete();
        }
        
        return redirect()->route('staff.index');
    }
}

resources/views/sections/staff/create.blade.php
@extends('containers.content')

@section('content')
<div class="container-fluid not-separated">
    <div class="row">
        <div class="save-bar">
            <a href="{{ route('staff.index') }}" class="btn btn-duo">Cancelar</a>
            <input type="button" class="btn btn-pri" value="Guardar" submit="#form-staff">
        </div>

        <div class="col-lg-10 offset-lg-1 col-xl-6 offset-xl-3">
            <div class="wrapper">
                @if(Route::currentRouteName() == 'staff.create')
                    {!! Form::open(['url' => route('staff.store'), 'method' => 'POST', 'id' => 'form-staff', 'files' => true, 'no-btn']) !!}
                @else
                    {!! Form::open(['url' => route('staff.update', ['user' => $user->id]), 'method' => 'PATCH', 'id' => 'form-staff', 'files' => true, 'no-btn']) !!}
                @endif
                    <div class="row">
                        <div class="col-md-12 section-row">
                            <div class="form-field form-field-image">
                                <label for="image" class="form-label">Foto</label>
                                {!! Form::file('image', ['id' => 'image', 'class' => 'form-input', 'autofocus']) !!}
                                <label for="image" class="form-file">
                                    @if(isset($user))
                                        <img src="{{ $user->image }}" alt="{{ $user->name }}">
                                    @else
                                        <img src="" alt="">
                                    @endif
                                    <span class="form-file-message">
                                        <span>Arrastra tu imagen</span>
                                        <span>500 x 500</span>
                                    </span>
                                </label>
                                
                                @if($errors->get('image'))
                                    <div class="alert alert-danger">
                                        {{ $errors->first('image') }}
                                    </div>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-field">
                                <label for="" class="form-label">Asignar rol</label>
                                
                                <ul id="staff-role" class="roles-list">
                                    <li class="roles-item">
                                        <div class="form-radio">
                                            <input id="admin" type="radio" name="role" value="{{ App\Branch::ROLE_ADMIN }}"
                                            {{ old('role') == App\Branch::ROLE_ADMIN ? 'checked' : isset($user) && $user->type == App\Branch::ROLE_ADMIN ? 'checked' : 'checked' }}>
                                            <label for="admin">Administrador</label>
                                        </div>
                                    </li>

                                    <li class="roles-item">
                                        <div class="form-radio">
                                            <input id="staff" type="radio" name="role" value="{{ App\Branch::ROLE_STAFF }}"
                                            {{ old('role') == App\Branch::ROLE_STAFF ? 'checked' : isset($user) && $user->type == App\Branch::ROLE_STAFF ? 'checked' : '' }}>
                                            <label for="staff">Staff</label>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-field">
                                <label for="first-name" class="form-label">Nombres</label>
                                {!! Form::text('first_name', isset($user) ? $user->first_name : null, ['id' => 'first-name', 'class' => 'form-input', 'placeholder' => 'Nombres']) !!}

                                @if($errors->get('first_name'))
                                    <div class="alert alert-danger">
                                        {{ $errors->first('first_name') }}
                                    </div>
                                @endif
                            </div>

                            <div class="form-field">
                                <label for="last-name" class="form-label">Apellidos</label>
                                {!! Form::text('last_name', isset($user) ? $user->last_name : null, ['id' => 'last-name', 'class' => 'form-input', 'placeholder' => 'Apellidos']) !!}

                                @if($errors->get('last_name'))
                                    <div class="alert alert-danger">
                                        {{ $errors->first('last_name') }}
                                    </div>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div id="staff-birth" class="form-field" style="display: none;">
                                <label for="birthdate" class="form-label">Fecha de nacimiento (formato: 1990-01-25)</label>
                                {!! Form::text('birthdate', isset($user) ? $user->birthdate->format('Y-m-d') : null, ['id' => 'birthdate', 'class' => 'form-input', 'placeholder' => '1990-01-25']) !!}

                                @if($errors->get('birthdate'))
                                    <div class="alert alert-danger">
                                        {{ $errors->first('birthdate') }}
                                    </div>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div id="staff-email" class="form-field" style="display: none;">
                                <label for="email" class="form-label">Email</label>
                                {!! Form::text('email', isset($user) ? $user->email : null, ['id' => 'email', 'class' => 'form-input', 'placeholder' => 'ejemplo@email.com']) !!}

                                @if($errors->get('email'))
                                    <div class="alert alert-danger">
                                        {{ $errors->first('email') }}
                                    </div>
                                @endif
                            </div>
                        </div>

                        <div id="staff-branch-title" class="col-md-12" style="display: none;">
                            <h3 class="form-section">Asignar a una o varias empresas</h3>
                        </div>

                        <div id="staff-branches" class="col-md-12" style="display: none;">
                            <div class="v-preloading"></div>
                            <app-assign-companies :companies="{{ $companies }}" :branches="{{ $branches }}" :defaults="{{ isset($user) ? $user->staffing->load('company') : collect([]) }}"/>
                        </div>
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/sections/staff/index.blade.php
@extends('containers.content')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <form class="search-bar" method="GET" action="{{ action('StaffController@index') }}">
                <div class="form-search">
                    <i class="fa fa-search icon"></i>
                    <input id="search" type="text" class="form-input" name="name" placeholder="Buscar Integrante" value="{{ $name }}">
                </div>

                <div class="actions">
                    <a href="{{ route('staff.create') }}" class="action">
                        <i class="fa fa-plus icon"></i>
                        <span>Nuevo Intengrante</span>
                    </a>
                </div>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <ul class="tabs md">
                <li class="tab-item" tab="#tab-admin">Admin</li>
                <li class="tab-item" tab="#tab-staff">Staff</li>
            </ul>

            <!-- Tab Admin : BEGIN -->
            <div id="tab-admin" class="table table-members tab-wrapper">
                <table>
                    @if ($admins->count())
                        <thead>
                            <tr>
                                <th class="col-user">Datos</th>
                                <th class="col-companies"></th>
                                <th class="col-actions"></th>
                            </tr>
                        </thead>
                    @endif

                    <tbody>
                        @foreach ($admins as $user)
                            <tr>
                                <td class="col-user">
                                    <div class="user">
                                        @if ($user->image)
                                            <div class="user-image">
                                                <img src="{{ $user->image }}" alt="{{ $user->name }}">
                                            </div>
                                        @else
                                            <div class="user-image" style="background-color: @strToHex($user->name)">
                                                <p>{{ $user->initials }}</p>
                                            </div>
                                        @endif

                                        <p class="user-name" title="Aquiles Esquivel Madrazo">
                                            {{ $user->name }}
                                        </p>
                                    </div>
                                </td>
                                <td class="col-companies"></td>
                                <td class="col-actions">
                                    <div class="menu-points">
                                        <div class="point"></div>
                                        <div class="point"></div>
                                        <div class="point"></div>

                                        <div class="menu-points-dropdown">
                                            <form id="del-user-{{ $user->id }}" action="{{ route('staff.destroy', ['user' => $user->id]) }}" method="POST">
                                                {{ csrf_field() }}
                                                <input type="hidden" name="_method" value="DELETE">
                                                <a href="javascript:{}" onclick="document.getElementById('del-user-{{ $user->id }}').submit();" class="menu-action">Eliminar</a>
                                            </form>

                                            <a href="{{ route('staff.edit', ['user' => $user->id]) }}" class="menu-action">Editar</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

                @if (!$admins->count())
                    <div class="table-empty">
                        <p>Sin usuarios</p>
                    </div>
                @endif
            </div>
            <!-- Tab Admin : END -->

            <!-- Tab Staff : BEGIN -->
            <div id="tab-staff" class="table table-members tab-wrapper">
                <table>
                    @if ($staff->count())
                        <thead>
                            <tr>
                                <th class="col-user">Datos</th>
                                <th class="col-companies">Empresa asignada</th>
                                <th class="col-actions"></th>
                            </tr>
                        </thead>
                    @endif

                    <tbody>
                        @foreach ($staff as $user)
                            <tr>
                                <td class="col-user">
                                    <div class="user">
                                        @if ($user->image)
                                            <div class="user-image">
                                                <img src="{{ $user->image }}" alt="{{ $user->name }}">
                                            </div>
                                        @else
                                            <div class="user-image" style="background-color: @strToHex($user->name)">
                                                <p>{{ $user->initials }}</p>
                                            </div>
                                        @endif

                                        <p class="user-name" title="Aquiles Esquivel Madrazo">
                                            {{ $user->name }}
                                        </p>
                                    </div>
                                </td>
                                <td class="col-companies">{{ $user->staffing->pluck('name')->implode(', ') }}</td>
                                <td class="col-actions">
                                    <div class="menu-points">
                                        <div class="point"></div>
                                        <div class="point"></div>
                                        <div class="point"></div>

                                        <div class="menu-points-dropdown">
                                            <form id="del-user-{{ $user->id }}" action="{{ route('staff.destroy', ['user' => $user->id]) }}" method="POST">
                                                {{ csrf_field() }}
                                                <input type="hidden" name="_method" value="DELETE">
                                                <a href="javascript:{}" onclick="document.getElementById('del-user-{{ $user->id }}').submit();" class="menu-action">Eliminar</a>
                                            </form>
                                            <a href="{{ route('staff.edit', ['user' => $user->id]) }}" class="menu-action">Editar</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

                @if (!$staff->count())
                    <div class="table-empty">
                        <p>Sin usuarios</p>
                    </div>
                @endif
            </div>
            <!-- Tab Staff : END -->
        </div>
    </div>
</div>
@endsection