routes/web.php
<?php

use App\Http\Controllers\UsersController;
use App\Http\Controllers\admins;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::resource('users', 'UsersController', ['only' => ['edit', 'update']]);
    Route::resource('companies/{company}/branch/{branch}/staff', 'ClientStaffController', ['names' => 'branches.staff', 'parameters' => ['staff' => 'user']]);
    Route::resource('companies/{company}/admin', 'ClientAdminController', ['only' => ['store', 'destroy'], 'names' => 'company.staff', 'parameters' => ['admin' => 'user']]);

    // Company (branches).
    Route::get('/company/{company}/branches', 'ClientCompanyController@branches')->name('client.company.branches');
    Route::get('/company/{company}/admins', 'ClientCompanyController@admins')->name('client.company.admins');
    Route::get('/company/{company}/branches/create', 'ClientCompanyController@createBranch')->name('client.company.branches.create');
    Route::post('/company/{company}/branches', 'ClientCompanyController@storeBranch')->name('client.company.branches.store');
});

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'roles:admins']], function () {
    // GET.
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/reports', 'ReportsController@index')->name('reports.index');
    
    // Companies.
    Route::resource('companies', 'CompaniesController');
    Route::get('/companies/{company}/admins', 'CompaniesController@admins')->name('companies.admins');

    // Branches.
    Route::resource('companies/{company}/branches', 'BranchesController');
    Route::get('/companies/{company}/branches/{branch}/orders', 'BranchesController@orders')->name('branches.orders');
    Route::get('/companies/{company}/branches/{branch}/members', 'BranchesController@members')->name('branches.members');

    // Refactored Controllers.
    Route::resource('products', 'ProductsController');
    Route::resource('orders', 'OrdersController', ['only' => ['index', 'show', 'update']]);
    Route::resource('staff', 'StaffController', ['parameters' => ['staff' => 'user']]);

    // Notifications
    Route::get('notifications', 'NotificationsController@index');
    Route::get('notifications/read', 'NotificationsController@read');
});

Route::group(['prefix' => 'branch/{branch}', 'middleware' => ['auth', 'roles:clients']], function () {
    // General.
    Route::get('/', 'ClientHomeController@index')->name('client.home');
    Route::get('/services', 'ClientServicesController@index')->name('client.services.index');
    Route::get('/reports', 'ClientReportsController@index')->name('client.reports.index');

    // Company.
    Route::get('/company/{company}', 'ClientCompanyController@index')->name('client.company.index');
    Route::patch('/company/{company}/update_company', 'ClientCompanyController@updateCompany')->name('client.company.update-company');
    Route::patch('/company/{company}/update_branch', 'ClientCompanyController@updateBranch')->name('client.company.update-branch');

    // History.
    Route::get('/history', 'ClientHistoryController@index')->name('client.history.index');
    Route::get('/history/{order}', 'ClientHistoryController@show')->name('client.history.show');

    // Quote.
    Route::get('/quote', 'ClientProductsController@index')->name('client.products.index');
    Route::get('/quote/{quote}/add', 'ClientProductsController@add')->name('client.products.add');
    Route::get('/quote/{quote}/checkout', 'ClientProductsController@checkout')->name('client.products.checkout');
    Route::post('/quote/{quote}/make_checkout', 'ClientProductsController@store')->name('client.quote.make-checkout');
    Route::get('/quote/complete', 'ClientProductsController@complete')->name('client.quote.complete');
});

// Change password after invite an user.
Route::get('/complete/{token}', 'UsersController@complete')->name('users.complete');
Route::patch('/complete/{token}', 'UsersController@completeProfile')->name('users.complete-profile');

Route::get('/', function () { return redirect()->route('login'); });
Route::get('/home', 'HomeController@branch')->middleware(['auth']);
Route::get('/change_branch', 'ClientHomeController@branch')->middleware('auth');
Route::get('/register', function () { return abort(404); }); // Register not needed.

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Underscore\Types\Strings;

class User extends Authenticatable
{
    use Notifiable;

    const TYPE_SUPERADMIN = 'superadmin';
    const TYPE_ADMIN = 'admin';
    const TYPE_CLIENT = 'client';
    const TYPE_STAFF = 'staff';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email',
        'type',
        'first_name',
        'last_name',
        'birthdate',
        'image',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'birthdate'
    ];

    /**
     *
     */
    public function staffing(): BelongsToMany
    {
        return $this->belongsToMany(Branch::class, 'branch_has_staff');
    }

    /**
     *
     */
    public function companies(): BelongsToMany
    {
        return $this->belongsToMany(Company::class, 'company_has_user')->withPivot([
            'role'
        ]);
    }

    /**
     *
     */
    public function branches(): BelongsToMany
    {
        return $this->belongsToMany(Branch::class, 'branch_has_user')->withPivot([
            'role'
        ]);
    }

    /**
     *
     */
    public function getImageAttribute($image)
    {
        if (!$image) {
            return null;
        }
        
        if (Strings::startsWith($image, 'http')) {
            return $image;
        }

        return asset(Strings::replace($image, 'public', 'storage'));
    }

    /**
     * Returns the user's full name
     */
    public function getFullNameAttribute()
    {
        return $this->getNameAttribute();
    }

    /**
     * Returns the user's full name
     */
    public function getNameAttribute()
    {
        return $this->first_name.' '.$this->last_name;
    }

    /**
     * Returns the user's full name
     */
    public function getInitialsAttribute()
    {
        return strtoupper($this->first_name[0].$this->last_name[0]);
    }
}

app/Http/Controllers/BranchesController.php
<?php

namespace App\Http\Controllers;

use App\Branch;
use App\Company;
use App\Order;
use App\User;
use Illuminate\Http\Request;

class BranchesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Company $company)
    {
        // Get the companies and their non-completed orders
        $branches = $company->branches()->withCount(['orders' => function ($query) {
            $query->where('status', '!=', Order::STATUS_COMPLETED);
        }]);

        return view('sections.buildings.index', [
            'company' => $company,
            'branches' => $branches->get(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Company $company)
    {
        return view('sections.buildings.create', [
            'branch' => new Branch(),
            'company' => $company,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Company $company)
    {
        $request->validate([
            'name' => 'required',
            'phone' => 'required',
            'zipcode' => 'required|min:5',
            'neighborhood' => 'required',
            'street' => 'required',
            'number_ext' => 'required',
            // 'number_int' => 'required',
            'city' => 'required',
            'state' => 'required',
        ]);

        $branch = $company->branches()->create($request->all());

        return redirect()->route('branches.index', $company->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company, Branch $branch)
    {
        return view('sections.buildings.create', [
            'branch' => $branch,
            'company' => $company,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Company $company, Branch $branch)
    {
        $branch->update($request->all());

        return redirect()->route('branches.orders', [$company->id, $branch->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     *
     */
    public function orders(Request $request, Company $company, Branch $branch)
     {
        $orders = $branch->orders();

        if ($request->status) {
            $orders = $orders->where('status', $request->status);
        }

        if ($request->id) {
            $orders->find($request->id);
        }

        return view('sections.buildings.orders', [
            'company' => $company,
            'branch' => $branch,
            'status' => $request->status,
            'id' => $request->id,
            'orders' => $orders
                ->orderBy('id', 'DESC')
                ->paginate(25),
        ]);
    }

    /**
     *
     */
    public function members (Company $company, Branch $branch, Request $request)
    {
        $users = $branch->users();

        if ($request->name) {
            $users = $users
                ->where('first_name', 'LIKE', '%'.$request->name.'%')
                ->orWhere('last_name', 'LIKE', '%'.$request->name.'%')
                ->wherePivot('role', Branch::ROLE_STAFF);
        }

        $users = $users->get();
        $users = $users->merge($branch->kleanServicesStaff);

        return view('sections.buildings.members', [
            'company' => $company,
            'branch' => $branch,
            'users' => $users,
            'name' => $request->name,
            'user' => new User(),
        ]);
    }
}

resources/views/sections/clients/admins.blade.php
@extends('containers.content')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="client-bar">
                <div class="client-bar-left">
                    <div class="client-details">
                        <div class="client-image">
                            <img src="{{ $company->image }}" alt="{{ $company->name }}">
                        </div>

                        <div class="client-name">
                            <p>{{ $company->name }}</p>
                        </div>
                    </div>

                    <div class="client-section">
                        <p>Administradores</p>
                    </div>

                    <form class="form-search">
                        <i class="fa fa-search icon"></i>
                        <input id="search" type="text" class="form-input" name="name" placeholder="Buscar Integrantes" value="{{ $name }}">
                    </form>
                </div>

                <div class="client-bar-right">
                    <div class="actions">
                        <a href="{{ route('companies.edit', $company->id) }}" class="action">
                            <i class="fa fa-pencil icon"></i>
                            <span>Editar Cliente</span>
                        </a>

                        <a href="" class="action" modal="#modal-building-members">
                            <i class="fa fa-user icon"></i>
                            <span>Añadir Admin</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="table table-building-members">
                <table>
                    <tbody>
                        @foreach ($users as $user)
                            <tr>
                                <td class="col-user">
                                    <div class="user">
                                        @if ($user->image)
                                            <div class="user-image">
                                                <img src="{{ $user->image }}" alt="{{ $user->name }}">
                                            </div>
                                        @else
                                            <div class="user-image" style="background-color: @strToHex($user->name)">
                                                <p>{{ $user->initials }}</p>
                                            </div>
                                        @endif

                                        <p class="user-name" title="{{ $user->name }}">{{ $user->name }}</p>
                                    </div>
                                </td>
                                <td class="col-rol">{{ $user->pivot->role }}</td>
                                <td class="col-actions">
                                    <div class="menu-points">
                                        <div class="point"></div>
                                        <div class="point"></div>
                                        <div class="point"></div>

                                        <div class="menu-points-dropdown">
                                            <form method="POST" action="{{ route('company.staff.destroy', [
                                                'company' => $company->id,
                                                'user' => $user->id,
                                            ]) }}">
                                                {{ csrf_field() }}
                                                <input type="submit" class="menu-action" value="Eliminar">
                                                <input type="hidden" name="_method" value="DELETE">
                                            </form>

                                            <a data="{{ $user }}"
                                                class="menu-action"
                                                modal="#modal-building-members">
                                                Editar
                                            </a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

                @if (!$users->count())
                    <div class="table-empty">
                        <p>Sin usuarios.</p>
                    </div>
                @endif
            </div>
        </div>
    </div>

    <!-- # modals. -->
    <div class="modal-umbrella {{ session('modal') ? 'show' : '' }}">
        @include('components.modal-company-admin')
    </div>
</div>
@endsection

resources/views/sections/clients/create.blade.php
@extends('containers.content')

@section('content')
<div class="container-fluid not-separated">
    <div class="row">
        <div class="save-bar">
            <a href="{{ route('companies.index') }}" class="btn btn-duo">Cancelar</a>
            <input type="button" class="btn btn-pri" value="Guardar" submit="#form-client">
        </div>

        <div class="col-lg-10 offset-lg-1 col-xl-6 offset-xl-3">
            <div class="wrapper">
                {!!
                    Form::model($company, [
                        'route' => $company->id ? ['companies.update', $company->id] : 'companies.store',
                        'method' => $company->id ? 'PATCH' : 'POST',
                        'id' => 'form-client',
                        'files' => true,
                        'no-btn'
                    ])
                !!}
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-field form-field-image">
                                <label for="image" class="form-label">Logo</label>
                                <input id="image" type="file" class="form-input" name="image" autofocus>
                                <label for="image" class="form-file">
                                    <img src="{{ $company->image }}" alt="">
                                    <span class="form-file-message">
                                        <span>Arrastra tu imagen</span>
                                        <span>500 x 500</span>
                                    </span>
                                </label>

                                @if($errors->get('image'))
                                    <div class="alert alert-danger">
                                        {{ $errors->first('image') }}
                                    </div>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-section"></div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-field">
                                <label for="name" class="form-label">Nombre del cliente</label>
                                {{ Form::text('name', null, ['id' => 'name', 'class' => 'form-input', 'placeholder' => 'Nombre del cliente']) }}

                                @if($errors->get('name'))
                                    <div class="alert alert-danger">
                                        {{ $errors->first('name') }}
                                    </div>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-12">
                            <h3 class="form-section">El cliente se encuentra en</h3>
                        </div>

                        @if (!$company->country)
                            <div class="col-md-12">
                                <div class="preloading-countries v-preloading"></div>
                                <app-countries :countries="{{ $countries }}"/>

                                @if($errors->get('country_id'))
                                    <div class="alert alert-danger">
                                        {{ $errors->first('country_id') }}
                                    </div>
                                @endif
                            </div>
                        @else
                            <div class="col-md-12">
                                <div class="row section-row">
                                    <div class="col-md-3">
                                        <a href="" class="country-card active">
                                            <div class="country-card-image">
                                                <img src="{{ $company->country->image }}" alt="{{ $company->country->name }}">
                                            </div>

                                            <div class="country-card-name">
                                                <p>{{ $company->country->name }}</p>
                                            </div>
                                        </a>
                                    </div>

                                    <input type="hidden" name="country_id" value="{{ $company->country->id }}">
                                </div>
                            </div>
                        @endif

                        <div class="col-md-12">
                            <div class="form-field">
                                <label for="business-name" class="form-label">Razón social</label>
                                {{ Form::text('business_name', null, ['id' => 'business-name', 'class' => 'form-input', 'placeholder' => 'Cliente S.A. de C.V.']) }}

                                @if($errors->get('business_name'))
                                    <div class="alert alert-danger">
                                        {{ $errors->first('business_name') }}
                                    </div>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-field">
                                <label for="rfc" class="form-label">RFC / NIT</label>
                                {{ Form::text('tin', null, ['id' => 'rfc', 'class' => 'form-input', 'placeholder' => 'RFC / NIT']) }}

                                @if($errors->get('tin'))
                                    <div class="alert alert-danger">
                                        {{ $errors->first('tin') }}
                                    </div>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-12">
                            <h3 class="form-section">Dirección de facturación</h3>
                        </div>

                        <div class="col-md-4">
                            <div class="form-field">
                                <label for="zipcode" class="form-label">Código Postal</label>
                                {{ Form::text('zipcode', null, ['id' => 'zipcode', 'class' => 'form-input', 'placeholder' => '44100']) }}

                                @if($errors->get('zipcode'))
                                    <div class="alert alert-danger">
                                        {{ $errors->first('zipcode') }}
                                    </div>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-8">
                            <div class="form-field">
                                <label for="suburb" class="form-label">Colonia</label>
                                {{ Form::text('neighborhood', null, ['id' => 'suburb', 'class' => 'form-input', 'placeholder' => 'Colonia']) }}
                                
                                @if($errors->get('neighborhood'))
                                    <div class="alert alert-danger">
                                        {{ $errors->first('neighborhood') }}
                                    </div>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-field">
                                <label for="street" class="form-label">Calle</label>
                                {{ Form::text('street', null, ['id' => 'street', 'class' => 'form-input', 'placeholder' => 'Calle']) }}

                                @if($errors->get('street'))
                                    <div class="alert alert-danger">
                                        {{ $errors->first('street') }}
                                    </div>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-field">
                                <label for="num-ext" class="form-label">N. Exterior</label>
                                {{ Form::text('number_ext', null, ['id' => 'num-ext', 'class' => 'form-input', 'placeholder' => 'XX']) }}

                                @if($errors->get('number_ext'))
                                    <div class="alert alert-danger">
                                        {{ $errors->first('number_ext') }}
                                    </div>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-field">
                                <label for="num-int" class="form-label">N. Interior</label>
                                {{ Form::text('number_int', null, ['id' => 'num-int', 'class' => 'form-input', 'placeholder' => 'XX']) }}

                                @if($errors->get('number_int'))
                                    <div class="alert alert-danger">
                                        {{ $errors->first('number_int') }}
                                    </div>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-field">
                                <label for="city" class="form-label">Ciudad</label>
                                {{ Form::text('city', null, ['id' => 'city', 'class' => 'form-input', 'placeholder' => 'Ciudad']) }}

                                @if($errors->get('city'))
                                    <div class="alert alert-danger">
                                        {{ $errors->first('city') }}
                                    </div>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-field">
                                <label for="state" class="form-label">Estado / Departamento</label>
                                {{ Form::text('state', null, ['id' => 'state', 'class' => 'form-input', 'placeholder' => 'Estado / Departamento']) }}

                                @if($errors->get('state'))
                                    <div class="alert alert-danger">
                                        {{ $errors->first('state') }}
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/sections/clients/index.blade.php
@extends('containers.content')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <form class="search-bar" method="GET" action="{{ action('CompaniesController@index') }}">
                <div class="form-search">
                    <i class="fa fa-search icon"></i>
                    <input id="search" type="text" class="form-input" name="search" placeholder="Buscar Clientes" value="{{ $search }}">
                </div>

                <div class="actions">
                    <a href="{{ route('companies.create') }}" class="action">
                        <i class="fa fa-plus icon"></i>
                        <span>Nuevo Cliente</span>
                    </a>
                </div>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <p class="counter clients-counter">{{ $companies->count() }} cliente{{ $companies->count() == 1 ? '' : 's' }}</p>
        </div>

        @foreach ($companies as $company)
            <div class="col-lg-4 col-xl-2">
                <a href="{{ route('branches.index', ['client' => $company->id]) }}" class="client-card">
                    <div class="client-card-logo">
                        <img src="{{ $company->image }}" alt="{{ $company->name }}">
                    </div>

                    <div class="client-card-name">
                        <p title="{{ $company->name }}">{{ $company->name }}</p>
                    </div>

                    @if ($company->orders_count)
                        <div class="client-card-status">
                            <p>{{ $company->orders_count }} pedido{{ $company->orders_count == 1 ? '' : 's' }} pendientes</p>
                        </div>
                    @else
                        <div class="client-card-status-empty">
                            <p>0 pedidos pendientes</p>
                        </div>
                    @endif
                </a>
            </div>
        @endforeach

        @if (!$companies->count())
            <div class="col-md-12">
                <p class="empty">Sin clientes.</p>
            </div>
        @endif
    </div>
</div>
@endsection